if(JEMALLOC_PATH)	
	find_path(JEMALLOC_INCLUDE_DIRS NAMES "jemalloc/jemalloc.h" PATHS ${JEMALLOC_PATH})
	find_library(JEMALLOC_LIBRARIES NAMES "jemalloc.lib" "libjemalloc.a" PATHS ${JEMALLOC_PATH})
else()
	find_path(JEMALLOC_INCLUDE_DIRS NAMES "jemalloc/jemalloc.h")
	find_library(JEMALLOC_LIBRARIES NAMES "jemalloc.lib" "libjemalloc.a")
endif()
if(JEMALLOC_INCLUDE_DIRS)
	if(JEMALLOC_LIBRARIES)
		set(JEMALLOC_FOUND)
		message(STATUS "--Found Jemalloc Library ${JEMALLOC_LIBRARIES}")
		message(STATUS "--Found Jemalloc Include ${JEMALLOC_INCLUDE_DIRS}")
	endif()
endif()